SELECT DISTINCT
  p.*,
  d.PLAN_ID
FROM SYS_PLAN p
  LEFT OUTER JOIN SYS_PLAN_DEPENDENCY d
    ON p.ID_PK = d.PLAN_ID
WHERE d.PLAN_ID IS NULL
START WITH p.TASK_ID = 2
CONNECT BY NOCYCLE PRIOR d.DEPENDENCY_ID = p.ID
ORDER BY d.PLAN_ID;

SELECT DISTINCT e.*
FROM SYS_EXECUTION e
LEFT OUTER JOIN SYS_EXECUTION_DEPENDENCY d
ON e.ID_PK = d.EXECUTION_ID
WHERE d.EXECUTION_ID IS NULL
  --AND e.START_DATE IS NULL
  AND e.STOP_DATE IS NULL
  AND ACTIVE = '1'
START WITH e.TASK_ID = 2
CONNECT BY PRIOR d.DEPENDENCY_ID = e.ID_;


SELECT *
FROM SYS_EXECUTION;

UPDATE SYS_EXECUTION
SET START_DATE = NULL, STOP_DATE = NULL
WHERE START_DATE IS NOT NULL OR STOP_DATE IS NOT NULL;


DELETE FROM SRC_DLBTH;
DELETE FROM SRC_SCHEDULE_FLOW;
DELETE FROM SRC_SCHEDULE;
DELETE FROM SRC_DEAL;
DELETE FROM SRC_FACILITY;
DELETE FROM DIC_ACCOUNT;
DELETE FROM DIC_CUSTOMER;
DELETE FROM DIC_CURRATE;
DELETE FROM DIC_CAL;
DELETE FROM DIC_SCHEDULE_TYPE;
DELETE FROM DIC_RESTRUCT_TYPE;
DELETE FROM DIC_EVENT_TYPE;
DELETE FROM DIC_CREDIT_TYPE;
COMMIT;

SELECT
  (SELECT count(*) FROM SRC_DLBTH) AS DLBTH,
  (SELECT count(*) FROM SRC_SCHEDULE_FLOW) AS FLOW,
  (SELECT count(*) FROM SRC_SCHEDULE) AS SCHEDULE,
  (SELECT count(*) FROM SRC_DEAL) AS DEAL,
  (SELECT count(*) FROM SRC_FACILITY) AS FACILITY,
  (SELECT count(*) FROM DIC_ACCOUNT) AS ACCOUNTS,
  (SELECT count(*) FROM DIC_CUSTOMER) AS CUSTOMERS,
  (SELECT count(*) FROM DIC_CURRATE) AS RATES,
  (SELECT count(*) FROM DIC_CAL) AS CALENDARS,
  (SELECT count(*) FROM DIC_CURRENCY) AS CURRENCIES,
  (SELECT count(*) FROM DIC_SCHEDULE_TYPE) AS SCHEDULE_TYPES,
  (SELECT count(*) FROM DIC_RESTRUCT_TYPE) AS RESTRUCT_TYPES,
  (SELECT count(*) FROM DIC_EVENT_TYPE) AS EVENT_TYPES,
  (SELECT count(*) FROM DIC_CREDIT_TYPE) AS CREDIT_TYPES
FROM DUAL;