SELECT p.*, d.PLAN_ID
FROM SYS_PLAN p
  LEFT OUTER JOIN SYS_PLAN_DEPENDENCY d
    ON p.ID_PK = d.PLAN_ID
START WITH p.TASK_ID = 2
CONNECT BY PRIOR d.DEPENDENCY_ID = p.ID
ORDER BY d.PLAN_ID;

-- Выбираем дерево элементов плана из графа
SELECT DISTINCT p.ID, p.ALIAS, p,NAME, p.TASK_ID, d.PLAN_ID
FROM SYS_PLAN p
  LEFT OUTER JOIN SYS_PLAN_DEPENDENCY d
    ON p.ID_PK = d.PLAN_ID
START WITH p.TASK_ID = 2
CONNECT BY NOCYCLE PRIOR d.DEPENDENCY_ID = p.ID
ORDER BY d.PLAN_ID;

-- Выбираем независимые элементы плана из графа
SELECT DISTINCT p.*, d.PLAN_ID
FROM SYS_PLAN p
  LEFT OUTER JOIN SYS_PLAN_DEPENDENCY d
    ON p.ID_PK = d.PLAN_ID
WHERE d.PLAN_ID is null
START WITH p.TASK_ID = 2
CONNECT BY NOCYCLE PRIOR d.DEPENDENCY_ID = p.ID
ORDER BY d.PLAN_ID;

select * from SYS_PLAN p
  LEFT OUTER JOIN SYS_PLAN_DEPENDENCY d
    ON p.ID_PK = d.PLAN_ID
WHERE d.DEPENDENCY_ID is null;




--
--
--
-- EXECUTION
--
--
--
--

-- выбираем все дерево запросов из графа
SELECT DISTINCT
  e.ID,
  e.ALIAS,
  e.NAME,
  e.TASK_ID,
  d.EXECUTION_ID
FROM SYS_EXECUTION e
  LEFT OUTER JOIN SYS_EXECUTION_DEPENDENCY d
    ON e.ID = d.EXECUTION_ID
WHERE ACTIVE = 1
START WITH e.TASK_ID = 3
CONNECT BY PRIOR d.DEPENDENCY_ID = e.ID
ORDER BY d.EXECUTION_ID;


-- выбираем независимые запросы по дереву запросов из графа
SELECT DISTINCT
  e.ID,
  e.ALIAS,
  e.START_DATE,
  e.STOP_DATE,
  e.NAME,
  e.TASK_ID,
  d.EXECUTION_ID
FROM SYS_EXECUTION e
  LEFT OUTER JOIN SYS_EXECUTION_DEPENDENCY d
    ON e.ID = d.EXECUTION_ID
WHERE d.EXECUTION_ID IS NULL AND e.START_DATE IS NULL AND e.STOP_DATE IS NULL AND ACTIVE = '1'
START WITH e.TASK_ID = 3
CONNECT BY PRIOR d.DEPENDENCY_ID = e.ID
ORDER BY d.EXECUTION_ID;

-- step 1. start independent plan jobs
UPDATE SYS_EXECUTION SET START_DATE = CURRENT_TIMESTAMP WHERE ID = 15;
UPDATE SYS_EXECUTION SET START_DATE = CURRENT_TIMESTAMP WHERE ID = 8;
UPDATE SYS_EXECUTION SET START_DATE = CURRENT_TIMESTAMP WHERE ID = 12;
UPDATE SYS_EXECUTION SET START_DATE = CURRENT_TIMESTAMP WHERE ID = 16;

-- step 2. plan job 15 finished
UPDATE SYS_EXECUTION SET STOP_DATE = CURRENT_TIMESTAMP WHERE ID = 15;
DELETE FROM SYS_EXECUTION_DEPENDENCY WHERE DEPENDENCY_ID = 15;
-- step 3. plan job 16 finished
UPDATE SYS_EXECUTION SET STOP_DATE = CURRENT_TIMESTAMP WHERE ID = 16;
DELETE FROM SYS_EXECUTION_DEPENDENCY WHERE DEPENDENCY_ID = 16;
-- step 4. start independent plan job 14
UPDATE SYS_EXECUTION SET START_DATE = CURRENT_TIMESTAMP WHERE ID = 14;
-- step 5. plan job 8 finished
UPDATE SYS_EXECUTION SET STOP_DATE = CURRENT_TIMESTAMP WHERE ID = 8;
DELETE FROM SYS_EXECUTION_DEPENDENCY WHERE DEPENDENCY_ID = 8;
-- step 6. plan job 12 finished
UPDATE SYS_EXECUTION SET STOP_DATE = CURRENT_TIMESTAMP WHERE ID = 12;
DELETE FROM SYS_EXECUTION_DEPENDENCY WHERE DEPENDENCY_ID = 12;
-- step 7. start independent plan job 13
UPDATE SYS_EXECUTION SET START_DATE = CURRENT_TIMESTAMP WHERE ID = 13;
-- step 8. plan job 14 finished
UPDATE SYS_EXECUTION SET STOP_DATE = CURRENT_TIMESTAMP WHERE ID = 14;
DELETE FROM SYS_EXECUTION_DEPENDENCY WHERE DEPENDENCY_ID = 14;
-- step 9. plan job 13 finished
UPDATE SYS_EXECUTION SET STOP_DATE = CURRENT_TIMESTAMP WHERE ID = 13;
DELETE FROM SYS_EXECUTION_DEPENDENCY WHERE DEPENDENCY_ID = 13;
-- step 10. start independent plan job 17
UPDATE SYS_EXECUTION SET START_DATE = CURRENT_TIMESTAMP WHERE ID = 17;
-- step 11. plan job 17 finished
UPDATE SYS_EXECUTION SET STOP_DATE = CURRENT_TIMESTAMP WHERE ID = 17;
DELETE FROM SYS_EXECUTION_DEPENDENCY WHERE DEPENDENCY_ID = 17;
-- step 12. start independent plan job 18
UPDATE SYS_EXECUTION SET START_DATE = CURRENT_TIMESTAMP WHERE ID = 18;
-- step 13. plan job 18 finished
UPDATE SYS_EXECUTION SET STOP_DATE = CURRENT_TIMESTAMP WHERE ID = 18;
DELETE FROM SYS_EXECUTION_DEPENDENCY WHERE DEPENDENCY_ID = 18;


-- выбираем запросы зависимые от набора выполненных запросов по дереву запросов из графа
SELECT DISTINCT
  e.ID,
  e.ALIAS,
  e.NAME,
  e.TASK_ID,
  d.EXECUTION_ID
FROM SYS_EXECUTION e
  LEFT OUTER JOIN SYS_EXECUTION_DEPENDENCY d
    ON e.ID = d.EXECUTION_ID
WHERE DEPENDENCY_ID IN (15, 8, 12, 16)
START WITH e.TASK_ID = 3
CONNECT BY PRIOR d.DEPENDENCY_ID = e.ID
ORDER BY d.EXECUTION_ID;

SELECT *
FROM SYS_PLAN p
  LEFT OUTER JOIN SYS_PLAN_DEPENDENCY d
    ON p.ID_PK = d.PLAN_ID
WHERE d.DEPENDENCY_ID IS NULL;
