CREATE TABLE DIC_CAL
(
    DAT DATE,
    HOL CHAR(1),
    CCY CHAR(3)
);


CREATE TABLE DIC_CURRATES
(
    DAT DATE,
    CCY CHAR(3),
    RATE NUMBER(15,9),
    AMNT NUMBER(6,2),
    RATE0 NUMBER(15,9)
);

CREATE TABLE DIC_CURRENCY
(
    GLCCY CHAR(3),
    CBCCY CHAR(3),
    CYNMEN VARCHAR2(14),
    CYNM VARCHAR2(35),
    NBDP NUMBER(1),
    DAT DATE
);




CREATE TABLE IRBIS.CCY
(
    ID NUMBER(19) PRIMARY KEY NOT NULL,
    GRNLT NUMBER(1),
    PRCS_MTL_FLG NUMBER(1),
    SPCL_CD VARCHAR2(3) NOT NULL
);
COMMENT ON COLUMN IRBIS.CCY.ID IS 'Суррогатный ключ, значение совпадает со значением ключа в таблице классификаторов (Code Table)';
COMMENT ON COLUMN IRBIS.CCY.GRNLT IS 'Число знаков после запятой';
COMMENT ON COLUMN IRBIS.CCY.PRCS_MTL_FLG IS '1 - драгметалл, 0 - обычная валюта.';
COMMENT ON COLUMN IRBIS.CCY.SPCL_CD IS 'Специальный дополнительный код валюты в классификации ЦБ РФ';
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (745, 2, 0, '051');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (746, 2, 0, '040');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (747, 2, 0, '036');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (748, 2, 0, '031');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (749, 2, 0, '050');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (750, 0, 0, '056');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (751, 0, 0, '974');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (752, 2, 0, '124');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (753, 2, 0, '756');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (754, 2, 0, '203');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (755, 2, 0, '276');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (756, 2, 0, '208');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (757, 2, 0, '233');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (758, 2, 0, '818');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (759, 0, 0, '724');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (760, 2, 0, '230');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (761, 2, 0, '978');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (762, 2, 0, '246');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (763, 2, 0, '250');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (764, 2, 0, '826');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (765, 2, 0, '981');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (766, 0, 0, '300');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (767, 2, 0, '344');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (768, 2, 0, '348');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (769, 2, 0, '372');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (770, 2, 0, '356');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (771, 0, 0, '380');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (772, 3, 0, '400');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (773, 0, 0, '392');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (774, 2, 0, '417');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (775, 2, 0, '398');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (776, 2, 0, '440');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (777, 2, 0, '428');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (778, 2, 0, '504');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (779, 2, 0, '498');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (780, 2, 0, '470');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (781, 2, 0, '528');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (782, 2, 0, '578');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (783, 2, 0, '554');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (784, 2, 0, '616');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (785, 0, 0, '620');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (786, 2, 0, '643');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (787, 2, 0, '752');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (788, 2, 0, '702');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (789, 0, 0, '762');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (790, 2, 0, '972');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (791, 2, 0, '795');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (792, 2, 0, '980');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (793, 2, 0, '804');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (794, 2, 0, '840');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (795, 2, 0, '860');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (796, 2, 0, 'P72');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (797, 2, 0, 'C84');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (798, 2, 0, 'C44');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (799, 2, 0, 'C95');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (800, 2, 0, '954');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (801, 2, 0, 'C45');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (802, 2, 0, 'C97');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (803, 2, 0, 'C57');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (804, 2, 0, '944');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (805, 2, 0, '985');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (806, 2, 0, '196');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (807, 2, 0, '352');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (808, 2, 0, '682');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (809, 2, 0, '934');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (810, 2, 0, '156');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (811, 2, 0, '975');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (812, 2, 0, '496');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (813, 2, 0, '941');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (814, 2, 0, '764');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (815, 2, 0, '946');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (816, 2, 1, 'A99');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (817, 2, 0, '933');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (818, 2, 0, '104');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (819, 2, 0, '108');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (820, 2, 0, '116');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (821, 2, 0, '132');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (822, 2, 0, '136');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (823, 0, 0, '144');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (824, 0, 0, '152');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (825, 2, 0, '170');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (826, 2, 0, '174');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (827, 2, 0, '188');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (828, 2, 0, '191');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (829, 2, 0, '192');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (830, 2, 0, '214');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (831, 2, 0, '222');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (832, 0, 0, '232');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (833, 2, 0, '238');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (834, 2, 0, '242');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (835, 2, 0, '262');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (836, 2, 0, '270');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (837, 2, 0, '292');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (838, 0, 0, '152');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (839, 2, 0, '170');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (840, 2, 0, '174');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (841, 2, 0, '188');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (842, 2, 0, '191');
INSERT INTO IRBIS.CCY (ID, GRNLT, PRCS_MTL_FLG, SPCL_CD) VALUES (843, 2, 0, '192');